version: '3.8'

services:

  wordpress:
    depends_on:
      - "postgres"
    build: .
    image: custom-wordpress-postgresql:latest
    restart: always
    ports:
      - 9000:80
    environment:
      WORDPRESS_DB_HOST: postgres
      WORDPRESS_DB_USER: postgres
      WORDPRESS_DB_PASSWORD: postgres
      WORDPRESS_DB_NAME: postgres
    volumes:
      - ./wp:/var/www/html

  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
  
  

volumes:
  db:
    
     
